spring:
  application:
    name: api-catalog

  datasource:
    url: jdbc:postgresql://localhost:5433/threadly_catalog
    username: threadly
    password: threadly

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8081

security:
  jwt:
    secret: ${THREADLY_JWT_SECRET}
    issuer: threadly-auth