spring:
  application:
    name: api-catalog

  datasource:
    url: jdbc:postgresql://localhost:5433/threadly_catalog
    username: threadly
    password: threadly

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true