spring:
  application:
    name: api-auth

  datasource:
    url: jdbc:postgresql://localhost:5433/threadly_auth
    username: threadly
    password: threadly

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

security:
  jwt:
    secret: ${THREADLY_JWT_SECRET}
    expiration: 900000
    issuer: threadly-auth